nelmio_api_doc:
    documentation:
        info:
            title: Shop doc
            description: This is an example shop doc
            version: 1.0.0
    areas: # to filter documented areas

        path_patterns:
#            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
