# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app:api_per_age: '%env(int:ITEMS_PER_PAGE)%'
    app:import_product_author: '%env(int:IMPORT_PRODUCT_AUTHOR)%'
    app:order_created_status: '%env(ORDER_CREATED_STATUS)%'
    app:retailcrm:country_iso: '%env(COUNTRY_ISO)%'
    app:retailcrm:order_type: '%env(RETAIL_CRM_ORDER_TYPE)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\ProductImport:
        $fortnite_api_url: '%env(FORTNITE_API_URL)%'
        $fortnite_api_key: '%env(FORTNITE_API_KEY)%'

    App\Service\Mailer:
        $email_from: '%env(EMAIL_FROM_ADDRESS)%'
        $email_to: '%env(EMAIL_TO_ADDRESS)%'

    App\Service\RetailCrm\ProductManager:
        $url: '%env(RETAIL_CRM_URL)%'
        $apiKey: '%env(RETAIL_CRM_API_KEY)%'
    App\Service\RetailCrm\OffersManager:
        $url: '%env(RETAIL_CRM_URL)%'
        $apiKey: '%env(RETAIL_CRM_API_KEY)%'
    App\Service\RetailCrm\OrderManager:
        $url: '%env(RETAIL_CRM_URL)%'
        $apiKey: '%env(RETAIL_CRM_API_KEY)%'
    App\Service\RetailCrm\CustomerManager:
        $url: '%env(RETAIL_CRM_URL)%'
        $apiKey: '%env(RETAIL_CRM_API_KEY)%'

#    App\EventSubscriber\ExceptionResponseSubscriber:
#        tags:
#            - { name: kernel.event_subscriber, event: kernel.exception }


    app.normalizer.object_normalizer:
        parent: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
        tags: [ "serializer.normalizer" ]
        arguments:
            $propertyInfoExtractor: null
            $defaultContext:
                circular_reference_handler: '@App\Serializer\CircularReferenceHandler'
                #        ignored_attributes: [ 'insertedOn', 'updatedOn', 'createdAt', 'updatedAt' ]
                ignored_attributes: [ 'createdAt' ]
                callbacks: {
                    'updatedAt': '@App\Serializer\UpdatedAtCallback'
                }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
